[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.17.0"
  # DO NOT set actual API keys here - use Netlify environment variables instead

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Netlify Identity settings
[template.environment]
  NETLIFY_IDENTITY_ENABLED = "true"

# Redirect for Netlify Identity Widget
[[redirects]]
  from = "/admin/*"
  to = "/admin/:splat"
  status = 200

# Add a non-root 404 page for admin paths
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 404

# Add security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data:; connect-src 'self' https://*.googleapis.com;"