[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.17.0"
  NEXT_PUBLIC_GEMINI_API_KEY = "insert_your_api_key_here"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Netlify Identity settings
[template.environment]
  NETLIFY_IDENTITY_ENABLED = "true"

# Redirect for Netlify Identity Widget
[[redirects]]
  from = "/admin/*"
  to = "/admin/:splat"
  status = 200

# Add a non-root 404 page for admin paths
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 404
