[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.17.0"
  NEXT_PUBLIC_GEMINI_API_KEY = "insert_your_api_key_here"

[[plugins]]
  package = "@netlify/plugin-nextjs"
